collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8740433135535568
color:
  saturation: 0.3530466
  brandStrength: 0
  lightness: 0.8548387
  brandColors:
    - '#FDFDFD'
    - '#020204'
    - '#322E29'
    - '#7C7971'
    - '#B5AA8C'
  rhythmicContrast: 0.3033647
layout_spectrum: 0.3743276875466108
name: Fine & Dandy
